### ISSUE TITLE
TH Level

### ISSUE THREAD

**Issue by ijustread** [Sakatland/SCS#1]
Is it possible to include the TH level of the attacker & defender in this data file: "08 - CWL Members Stats"? (I'm using the exe version)

This is a very helpful program, thanks for creating it.

**Comment by Sakatland** [comment]
Hey,

Sorry for very late replay. I only saw now your message!

Since you wrote your message I added the TH level of the clan members (in .txt file 08) but I did not added the one of the opponent. I don't plan to add it for the moment because the script is mainly useful for higher league where everyone is almost always TH13. But I'll keep the idea in mind. I'm glad you find the script useful. Cheers!


Sakat
